import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#fff",
  },
  header: {
    paddingTop: 60,
    paddingHorizontal: 20,
    paddingBottom: 20,
    backgroundColor: "#f8f9fa",
    borderBottomWidth: 1,
    borderBottomColor: "#eaeaea",
  },

  profileSection: {
    flexDirection: "row",
    alignItems: "center",
  },
  imageContainer: {
    marginRight: 15,
  },
  therapistImage: {
    width: 100,
    height: 100,
    borderRadius: 50,
    borderWidth: 2,
    borderColor: "#fff",
  },
  infoContainer: {
    flex: 1,
  },
  name: {
    fontSize: 24,
    fontWeight: "bold",
    color: "#333",
    marginBottom: 5,
  },
  specialty: {
    fontSize: 16,
    color: "#555",
    marginBottom: 8,
  },
  statsRow: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: 5,
  },
  statItem: {
    flexDirection: "row",
    alignItems: "center",
    marginRight: 15,
  },
  statText: {
    color: "#666",
    fontSize: 14,
    marginLeft: 5,
  },
  content: {
    flex: 1,
    padding: 20,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#333",
    marginBottom: 15,
    marginTop: 10,
  },
  aboutText: {
    fontSize: 15,
    color: "#555",
    lineHeight: 24,
  },
  infoRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 15,
  },
  infoIcon: {
    marginRight: 10,
    width: 24,
    alignItems: "center",
  },
  infoLabel: {
    fontSize: 15,
    color: "#666",
    width: 100,
  },
  infoValue: {
    fontSize: 15,
    color: "#333",
    flex: 1,
  },
  availabilityItem: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    padding: 16,
    backgroundColor: "#fff",
    borderRadius: 10,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: "#eee",
  },
  availabilityContent: {
    flexDirection: "row",
    alignItems: "center",
  },
  availabilityText: {
    fontSize: 15,
    color: "#333",
    marginLeft: 12,
  },
  noAvailabilityContainer: {
    alignItems: "center",
    paddingVertical: 30,
  },
  noAvailabilityText: {
    fontSize: 15,
    color: "#666",
    marginTop: 10,
  },
  reviewContainer: {
    marginBottom: 15,
    backgroundColor: "#f9f9f9",
    borderRadius: 10,
    padding: 15,
  },
  reviewHeader: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 10,
  },
  reviewerImage: {
    width: 40,
    height: 40,
    borderRadius: 20,
    marginRight: 10,
  },
  reviewerName: {
    fontWeight: "bold",
    fontSize: 15,
    color: "#333",
  },
  reviewDate: {
    fontSize: 12,
    color: "#777",
    marginLeft: "auto",
  },
  ratingContainer: {
    flexDirection: "row",
    marginBottom: 8,
  },
  reviewText: {
    fontSize: 14,
    color: "#555",
    lineHeight: 20,
  },
  buttonContainer: {
    padding: 20,
    paddingBottom: 30,
    backgroundColor: "#fff",
    borderTopWidth: 1,
    borderTopColor: "#eaeaea",
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: -3,
    },
    shadowOpacity: 0.1,
    shadowRadius: 3,
    elevation: 5,
  },
  bookButton: {
    backgroundColor: "#4a6ee0",
    borderRadius: 10,
    padding: 15,
    alignItems: "center",
  },
  bookButtonText: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "bold",
  },
  sectionDivider: {
    height: 8,
    backgroundColor: "#f5f5f5",
    marginVertical: 15,
  },
  tabContainer: {
    flexDirection: "row",
    borderBottomWidth: 1,
    borderBottomColor: "#eaeaea",
    marginBottom: 15,
  },
  tabButton: {
    flex: 1,
    paddingVertical: 15,
    alignItems: "center",
  },
  activeTab: {
    borderBottomWidth: 2,
    borderBottomColor: "#4E9CAF",
  },
  tabText: {
    fontSize: 16,
  },
  activeTabText: {
    fontWeight: "bold",
    color: "#4E9CAF",
  },
  inactiveTabText: {
    fontWeight: "normal",
    color: "#666",
  },
  certificateItem: {
    flexDirection: "row",
    backgroundColor: "#fff",
    borderRadius: 10,
    padding: 12,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: "#eee",
  },
  certificateImage: {
    width: 60,
    height: 60,
    borderRadius: 8,
    marginRight: 12,
  },
  certificateInfo: {
    flex: 1,
  },
  certificateTitle: {
    fontSize: 16,
    fontWeight: "600",
    color: "#333",
    marginBottom: 4,
  },
  certificateCategory: {
    fontSize: 14,
    color: "#666",
    marginBottom: 4,
  },
  certificateDate: {
    fontSize: 12,
    color: "#888",
    marginBottom: 6,
  },
  certificateStatus: {
    alignSelf: "flex-start",
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 12,
  },
  certificateStatusText: {
    fontSize: 12,
    fontWeight: "500",
  },
  noCertificatesText: {
    textAlign: "center",
    color: "#666",
    fontStyle: "italic",
    marginTop: 10,
  },
  verifiedBadge: {
    position: "absolute",
    bottom: 0,
    right: 0,
    backgroundColor: "#fff",
    borderRadius: 12,
    padding: 2,
  },
  availabilityHint: {
    fontSize: 14,
    color: "#666",
    fontStyle: "italic",
    marginBottom: 15,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.5)",
    justifyContent: "center",
    alignItems: "center",
  },
  modalContainer: {
    width: "90%",
    maxHeight: "80%",
    backgroundColor: "#fff",
    borderRadius: 12,
    overflow: "hidden",
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  modalHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    padding: 15,
    borderBottomWidth: 1,
    borderBottomColor: "#eee",
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#333",
  },
  modalContent: {
    padding: 15,
    maxHeight: "70%",
  },
  inputLabel: {
    fontSize: 14,
    fontWeight: "600",
    color: "#555",
    marginBottom: 8,
    marginTop: 12,
  },
  input: {
    borderWidth: 1,
    borderColor: "#ddd",
    borderRadius: 8,
    padding: 12,
    fontSize: 16,
    backgroundColor: "#f9f9f9",
    marginBottom: 15,
  },
  textArea: {
    height: 100,
    textAlignVertical: "top",
  },
  therapistPreview: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#f8f9fa",
    padding: 10,
    borderRadius: 8,
    marginBottom: 15,
  },
  smallTherapistImage: {
    width: 40,
    height: 40,
    borderRadius: 20,
    marginRight: 10,
  },
  therapistPreviewName: {
    fontSize: 16,
    fontWeight: "500",
    color: "#333",
  },
  timeSlotPreview: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#f8f9fa",
    padding: 12,
    borderRadius: 8,
    marginBottom: 15,
  },
  timeSlotText: {
    fontSize: 16,
    marginLeft: 10,
    color: "#333",
  },
  modalFooter: {
    flexDirection: "row",
    justifyContent: "space-between",
    padding: 15,
    borderTopWidth: 1,
    borderTopColor: "#eee",
  },
  cancelButton: {
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#ddd",
    backgroundColor: "#f9f9f9",
    flex: 1,
    marginRight: 8,
    alignItems: "center",
  },
  cancelButtonText: {
    color: "#666",
    fontSize: 16,
    fontWeight: "500",
  },
  confirmButton: {
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 8,
    backgroundColor: "#4a6ee0",
    flex: 1,
    marginLeft: 8,
    alignItems: "center",
  },
  confirmButtonText: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "500",
  },
  packageList: {
    marginBottom: 15,
  },
  packageItem: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    padding: 12,
    backgroundColor: "#f9f9f9",
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#eee",
    marginBottom: 10,
  },
  selectedPackage: {
    borderColor: "#4a6ee0",
    backgroundColor: "rgba(74, 110, 224, 0.05)",
  },
  packageInfo: {
    flex: 1,
    marginRight: 10,
  },
  packageName: {
    fontSize: 16,
    fontWeight: "600",
    color: "#333",
    marginBottom: 4,
  },
  packageDescription: {
    fontSize: 13,
    color: "#666",
    marginBottom: 8,
  },
  packagePrice: {
    fontSize: 16,
    fontWeight: "700",
    color: "#4a6ee0",
  },
  packageMeta: {
    flexDirection: "row",
    alignItems: "center",
    flexWrap: "wrap",
  },
  discountTag: {
    backgroundColor: "#4CAF5020",
    paddingVertical: 2,
    paddingHorizontal: 6,
    borderRadius: 4,
    marginRight: 8,
    marginBottom: 4,
  },
  discountText: {
    color: "#4CAF50",
    fontSize: 12,
    fontWeight: "600",
  },
  noPackagesContainer: {
    padding: 15,
    backgroundColor: "#f8f8f8",
    borderRadius: 8,
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#eee",
    marginBottom: 15,
  },
  noPackagesText: {
    color: "#666",
    fontSize: 14,
  },
  disabledButton: {
    backgroundColor: "#b0b0b0",
    opacity: 0.7,
  },
  requiredMark: {
    color: "#F44336",
    fontWeight: "700",
  },
});
